-- PES Arena V1.4.6 - Rank Season V1
create table if not exists public.rank_seasons (
  season_number integer primary key,
  name text not null,
  started_at timestamptz,
  ended_at timestamptz,
  status text not null default 'active',
  placement_matches integer not null default 5,
  created_at timestamptz not null default now()
);
create table if not exists public.rank_season_snapshots (
  season_number integer primary key,
  snapshot_data jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.rank_season_rewards (
  id bigint generated by default as identity primary key,
  season_number integer not null,
  user_id uuid not null references public.users(id) on delete cascade,
  position integer not null,
  zcoin_reward integer not null default 0,
  lucky_box_reward integer not null default 0,
  lucky_box_used integer not null default 0,
  status text not null default 'granted',
  granted_at timestamptz not null default now(),
  unique(season_number,user_id)
);
insert into public.system_settings(setting_key,setting_value,updated_at)
values ('rank_season_current', jsonb_build_object(
  'season_number',1,'name','Season 1','started_at',null,'status','active','placement_matches',5
), now())
on conflict (setting_key) do nothing;
